# .github/workflows/android.yml
name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Use a recent version

    - name: Set up JDK 17
      uses: actions/setup-java@v4 # Use a recent version
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    # The wrapper script will download the appropriate gradle distribution (including the jar) if needed
    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Upload debug APK
      uses: actions/upload-artifact@v4 # Use a recent version
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
